// Example: bridging a Chopper service to `Result<T>`.
//
// In production, `_$PetsApi` is generated by `chopper_generator`
// (`dart run build_runner build`). The stub below intentionally throws so the
// snippet illustrates `.toResult()`'s failure path; in real code you would
// call your generated client directly.

// ignore: depend_on_referenced_packages
import 'package:chopper/chopper.dart';
import 'package:resilify/resilify_chopper.dart';

class Pet {
  const Pet({required this.id, required this.name});

  factory Pet.fromJson(Map<String, dynamic> json) =>
      Pet(id: json['id'] as String, name: json['name'] as String);

  final String id;
  final String name;
}

// In production:
// part 'pets_api.chopper.dart';
//
// @ChopperApi(baseUrl: '/pets')
// abstract class PetsApi extends ChopperService {
//   static PetsApi create([ChopperClient? client]) => _$PetsApi(client);
//   @Get(path: '/{id}')
//   Future<Response<Pet>> getPet(@Path() String id);
// }
abstract class PetsApi {
  Future<Response<Pet>> getPet(String id);
}

class _StubPetsApi implements PetsApi {
  @override
  Future<Response<Pet>> getPet(String id) async {
    // A real client would return a Chopper Response. The stub throws so this
    // example focuses on `.toResult()` translating the error.
    throw Exception('replace _StubPetsApi with the generated _\$PetsApi');
  }
}

Future<void> main() async {
  final PetsApi api = _StubPetsApi();

  final result = await api.getPet('demo').toResult(
        failureMapper: (response) => Failure.badResponse(
          code: response.statusCode,
          message: 'Pet API failed',
          cause: response.error,
        ),
      );

  result.when(
    success: (p) => print('pet: ${p.name}'),
    error: (f) => print('failed: ${f.message}'),
  );
}
