// Example: bridging a Retrofit-generated client to `Result<T>`.
//
// In a real app you would:
//   1. Annotate `UserApi` with `@RestApi(...)`.
//   2. Run `dart run build_runner build` to generate `user_api.g.dart`.
//   3. `part 'user_api.g.dart';` and replace the stub `_UserApi` below.
//
// This file is illustrative — it stubs the generated client so the snippet
// compiles standalone.

// retrofit + dio types come transitively via the generated client; we import
// dio directly here just for the stub.
// ignore: depend_on_referenced_packages
import 'package:dio/dio.dart';
import 'package:resilify/resilify_retrofit.dart';
// ignore: depend_on_referenced_packages
import 'package:retrofit/retrofit.dart';

class User {
  User({required this.id, required this.name});

  factory User.fromJson(Map<String, dynamic> json) =>
      User(id: json['id'] as int, name: json['name'] as String);

  final int id;
  final String name;
}

// In production this is generated by retrofit_generator:
// @RestApi(baseUrl: 'https://api.example.com')
// abstract class UserApi {
//   factory UserApi(Dio dio) = _UserApi;
//   @GET('/users/{id}')
//   Future<User> getUser(@Path('id') String id);
//
//   @GET('/users/{id}/full')
//   Future<HttpResponse<User>> getUserFull(@Path('id') String id);
// }
class UserApi {
  UserApi(this._dio);
  final Dio _dio;

  Future<User> getUser(String id) async {
    final response = await _dio.get<Map<String, dynamic>>('/users/$id');
    return User.fromJson(response.data!);
  }

  Future<HttpResponse<User>> getUserFull(String id) async {
    final response = await _dio.get<Map<String, dynamic>>('/users/$id');
    return HttpResponse(User.fromJson(response.data!), response);
  }
}

Future<void> main() async {
  final api = UserApi(Dio(BaseOptions(baseUrl: 'https://api.example.com')));

  // Future<T> -> Future<Result<T>>
  final user = await api.getUser('42').toResult();
  user.when(
    success: (u) => print('got user #${u.id}: ${u.name}'),
    error: (f) => print('failed: ${f.message}'),
  );

  // Future<HttpResponse<T>> -> Future<Result<T>>
  final full = await api.getUserFull('42').toResult();
  full.when(
    success: (u) => print('full user: ${u.name}'),
    error: (f) => print('failed: ${f.message}'),
  );
}
